# Generated by Django 2.1.7 on 2019-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore_django', '0002_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='products',
            field=models.TextField(null=True),
        ),
    ]
